version: '3.8'

services:
  webhook-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-sponsors-bot
    container_name: github-sponsors-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - webhook-network

  # Optional: Add a reverse proxy for HTTPS
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./nginx/www:/var/www/html
  #   depends_on:
  #     - webhook-bot
  #   networks:
  #     - webhook-network

networks:
  webhook-network:
    driver: bridge